/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticketsevent;

//import DB.connector;
import DB.DatabaseConnections ;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class DetailWisata2 extends javax.swing.JFrame {

    /**
     * Creates new form DetailWisata2
     */
    public DetailWisata2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtstok = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel1.setText("FARM HOUSE");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 42, 214, 38));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 86, 987, 10));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel2.setText("Liburan Nanti Udah Ada Refrensi Liburan?? Jika Belum Ke Farm House Ajaaa Keren Banget Lhoooo");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 102, 660, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel3.setText("Farmhouse Lembang bisa dikatakan tempat liburan terbaru di Bandung yang dikelola dengan baik. Keberadaannya semakin melengkapi tempat wisata di ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 125, -1, -1));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel4.setText("Lembang yang bisa Kamu kunjungi Berada tidak jauh dari pusat Lembang, popularitasnya melesat naik cukup cepat Dari awal dibuka");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 146, -1, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel5.setText("Diatas Itu Salah Satu Iconic Dari farmHouse Lhoo KEREN BANGET KANNNN?");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 656, 660, -1));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel6.setText("Di Farm House Hampir Semua desain atmosfer eropa, banyak spot unik yang pastinya bakal menarik untuk swafoto/selfie, dan di posting di media sosial");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 202, -1, -1));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel7.setText("Farmhouse Lembang sejauh ini menawarkan ‘wisata foto’ sebagai daya tarik utamanya tempat liburan ini cocok juga dikunjungi bersama keluarga");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 223, -1, -1));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel8.setText("dan sikecil; ada beberapa kandang binatang yang unik, pasti menarik buat anak kecil");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 244, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Wisata2/pictWisata2d.jpg"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 265, 855, 380));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel10.setText("Apa Sih Min Yang Buat Menarik Di Farm House ?");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 179, 660, -1));

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel11.setText(" Rumah Hobbit ini jadi salah satu objek favorit di Farmhouse Bandung. Rumah hobbit versi kecil ini ditata rapi dan indah, tempatnya instagrammable banget");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 679, -1, -1));

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel12.setText("Apa Lagi Ditambah Foto Dengan Costum Nyaa huuu.");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 695, -1, -1));

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel13.setText(" Di Sini Terdapat penyewaan kostum bergaya eropa Lhooo. Tentunya ini bakal bikin foto anda lebih unik bukan? beda dengan yang lain");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 721, -1, -1));

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel14.setText(" Anda bisa menyewa kostum, berfoto di set latar yang tersedia, ataupun berkeliling lokasi mencari tempat berfoto yang bagus.");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 742, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Wisata2/pictWisata2eeditsize.jpg"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 763, 855, -1));

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel16.setText("Kamu Masih Belum Puas Dengan Spot Foto Nya Tenang Disini Banyak Pilihan Lain Nya Kok : )");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 1154, 660, -1));

        jLabel17.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel17.setText("Banyak banget spot berfoto yang bagus disini. Anda tinggal berkeliling dan berfoto di berbagai tempat yang ada Suasana bangunan di Farm house Lembang ");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 1177, -1, -1));

        jLabel18.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel18.setText("bakal lebih terasa asyik di saat sepi Taman bunga dan bangunan disini ditata bergaya eropa dan cukup terawat jadi Kamu ngga bakal kehabisan tempat Selfiee");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 1198, -1, -1));

        jLabel19.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        jLabel19.setText("Apalagi kalau kebetulan sedang turun kabut, lebih keren suasananya");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 1219, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Wisata2/pictWisata2feditsize.jpg"))); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 1240, -1, -1));

        jLabel21.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel21.setText("Ya Kann Keren banget Yuk Tunggu Apalagi.. Untuk Pembelian Tiket Dibawah Yaa Scroll Terusss");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 1626, 660, -1));

        jLabel22.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel22.setText("Dan Untuk Lokasi FARM HOUSE LEMBANG ITU tepatnya ada di  Jl. Raya Lembang No.108, Gudangkahuripan, Lembang, Bandung Barat");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 1649, 987, -1));

        jLabel23.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel23.setText("dan Jangan Lupa Ajak Keluarga Atau Pasangan Yaaa");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 1672, 987, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 1706, 987, 10));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(3, 100));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 1730, -1, -1));

        jLabel28.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel28.setText("YUK DAPATKAN TIKET DENGAN CHECHOUT!");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1730, -1, 20));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jpg/back.png"))); // NOI18N
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 1760, -1, 36));

        jLabel29.setText("SISA TIKET YANG TERSEDIA");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 1730, -1, -1));

        txtstok.setEditable(false);
        txtstok.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtstok.setBorder(null);
        jPanel2.add(txtstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1770, 210, 30));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jpg/checkoutpicteditsize.png"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 1750, 110, 90));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(3, 100));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 1730, -1, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 1810, 230, -1));

        jLabel25.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel25.setText("CheckOut");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 1850, 60, -1));

        jScrollPane1.setViewportView(jPanel2);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1026, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1894, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
        MenuWisata2 m = new MenuWisata2 () ;
        m.show () ;
        hide () ;
    }//GEN-LAST:event_jLabel30MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      cekstok();
    }//GEN-LAST:event_formWindowActivated

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
        Pembayaran p = new Pembayaran () ;
        p.show () ;
        hide () ;
    }//GEN-LAST:event_jLabel24MouseClicked
PreparedStatement pst;
    Connection con;
    ResultSet rs;
    Statement st;

    
    public void cekstok()
    {
        con = new DatabaseConnections().setConnection();  
        String sql = "select * from obj.EVENTT where EVENTID = 'E0002'";
        try{       
             st = con.createStatement();
             rs = st.executeQuery(sql);
             
            rs.next();
{
                 int stok = rs.getInt("STOCK");
                 String a = Integer.toString(stok);
                 
                 txtstok.setText(a);
             }
        }
        catch (SQLException e){
        JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println(""+e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailWisata2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailWisata2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailWisata2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailWisata2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailWisata2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtstok;
    // End of variables declaration//GEN-END:variables
}
