package ticketsevent;
import java.sql.*;
import java.awt.HeadlessException;
import DB.DatabaseConnections ;
import DB.user;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author VINI
 */
public class Registrasi extends javax.swing.JFrame {
    Statement st;
    PreparedStatement pst;
    Connection con;
    ResultSet rs;
    /**
     * Creates new form Registrasi
     */
    public Registrasi() {
        initComponents();
    }
    public void refresh()
    {
        txtName.setText(null);
        Password.setText(null);
        birthdate.setDate(null);
        txtEmail.setText(null);
        noHP.setText(null);
    }
    
    public void executeSQLQuery(String query){
        try
        {
            con = new DatabaseConnections().setConnection();
            String query1 = query;
            st = con.createStatement();
            rs = st.executeQuery(query1);
            user user;
            JOptionPane.showMessageDialog(null, "Success");
        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, "Something Wrong. Username already used by an account");
            System.out.println("error");
        }
    }
    
    public void add()
    {
        try
        {
            //declare variabel 
            String username = txtName.getText();
            String pass = Password.getText();
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dates = sdf.format(birthdate.getDate());
                       
            String Email = txtEmail.getText();
            String nomorHP = noHP.getText();
     
            //validation rule        
            if ("".equals(username))
            {
                JOptionPane.showMessageDialog(null, "Empty Field Not allowed");
            }
         
            //connection with database 
            con = new DatabaseConnections().setConnection();
            String sql="insert into human.USERS (USERNAME, PASS, BIRTHDATE, EMAIL, PHONE)"
                     + "values(?,?,?,?,?)";
            
            pst = con.prepareStatement(sql);
            
            // for insert to database
            pst.setString(1, username);
            pst.setString(2, pass);
            pst.setString(3, dates);
            pst.setString(4, Email);
            pst.setString(5, nomorHP);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Have been Inserted Successfull");
            refresh();     
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            JOptionPane.showMessageDialog(this, "There is something eror, please try again" );
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BTNSIGNUP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BTNBACK = new javax.swing.JButton();
        noHP = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        birthdate = new com.toedter.calendar.JDateChooser();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BTNSIGNUP.setBackground(new java.awt.Color(102, 102, 102));
        BTNSIGNUP.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BTNSIGNUP.setText("SIGN UP");
        BTNSIGNUP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNSIGNUPMouseClicked(evt);
            }
        });
        getContentPane().add(BTNSIGNUP, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 110, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 110, 20));

        BTNBACK.setBackground(new java.awt.Color(102, 102, 102));
        BTNBACK.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BTNBACK.setText("BACK");
        BTNBACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBACKActionPerformed(evt);
            }
        });
        getContentPane().add(BTNBACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, -1, -1));

        noHP.setBackground(new java.awt.Color(0, 0, 51));
        noHP.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        noHP.setForeground(new java.awt.Color(153, 153, 153));
        noHP.setBorder(null);
        noHP.setOpaque(false);
        getContentPane().add(noHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 380, -1));

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 380, 10));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Handphone");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 110, 20));

        txtName.setBackground(new java.awt.Color(0, 0, 51));
        txtName.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(153, 153, 153));
        txtName.setBorder(null);
        txtName.setOpaque(false);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 380, -1));

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 380, 10));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 100, 20));

        txtEmail.setBackground(new java.awt.Color(0, 0, 51));
        txtEmail.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(153, 153, 153));
        txtEmail.setBorder(null);
        txtEmail.setOpaque(false);
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 390, -1));

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 380, 10));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BirthDate");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 100, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 100, -1));

        Password.setBackground(new java.awt.Color(0, 0, 51));
        Password.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setBorder(null);
        Password.setOpaque(false);
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 380, -1));

        jSeparator4.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator4.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 380, 10));

        birthdate.setBackground(new java.awt.Color(153, 153, 153));
        birthdate.setForeground(new java.awt.Color(102, 102, 102));
        birthdate.setOpaque(false);
        getContentPane().add(birthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 340, -1));

        jSeparator5.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 380, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jpg/home.plane.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 893, 508));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
 
    }//GEN-LAST:event_txtNameActionPerformed

    private void BTNBACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBACKActionPerformed
       Logins L = new Logins();
       L.show();
       hide();
    }//GEN-LAST:event_BTNBACKActionPerformed

    private void BTNSIGNUPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNSIGNUPMouseClicked
       add();
        Logins L = new Logins();
       L.show();
       hide();
    }//GEN-LAST:event_BTNSIGNUPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBACK;
    private javax.swing.JButton BTNSIGNUP;
    private javax.swing.JPasswordField Password;
    private com.toedter.calendar.JDateChooser birthdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField noHP;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
